# Generated by Django 3.2.24 on 2024-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_MineTPH', models.PositiveIntegerField()),
                ('ScrubberTPH', models.PositiveIntegerField()),
                ('ThickenerTPH', models.PositiveIntegerField()),
                ('CoarseGangueM3PH', models.PositiveIntegerField()),
                ('RecycleWaterM3PH', models.PositiveIntegerField()),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
    ]
