# Generated by Django 3.2.24 on 2024-02-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiation1',
            new_name='Beneficiation',
        ),
    ]
