# Generated by Django 3.2.24 on 2024-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0002_rename_beneficiation1_beneficiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('rom_feed_to_plant_dry_ta', models.PositiveIntegerField()),
                ('feed_to_leach_dry_ta', models.PositiveIntegerField()),
                ('ctfs_total_tailing_dry_ta', models.PositiveIntegerField()),
                ('lce_produced_dry_ta', models.PositiveIntegerField()),
                ('rom_li_content_ppm', models.PositiveIntegerField()),
                ('particle_size_distribution_f80_mm', models.PositiveIntegerField()),
                ('ore_bulk_density_transport_tm3', models.FloatField()),
                ('ore_moisture_total_loose_weight_percent', models.FloatField()),
                ('crushed_particle_size_p80_mm', models.PositiveIntegerField()),
                ('feed_to_attrition_circuit_dry_td', models.PositiveIntegerField()),
                ('discharge_screen_oversize_rom_percent', models.FloatField()),
                ('feed_particle_size_p80_microns', models.PositiveIntegerField()),
                ('overflow_particle_size_p80_microns', models.PositiveIntegerField()),
                ('underflow_particle_size_p80_microns', models.PositiveIntegerField()),
                ('coarse_material_rejection_dry_percent', models.FloatField()),
                ('thickener_underflow_pulp_density_weight_percent', models.FloatField()),
                ('flocculant_consumption_g_per_t', models.FloatField()),
                ('decanter_centrifuge_cake_density_weight_percent', models.FloatField()),
                ('feed_solids_li_content_ppm', models.PositiveIntegerField()),
                ('feed_pulp_density_weight_percent', models.FloatField()),
                ('leach_residence_time_minutes', models.PositiveIntegerField()),
                ('neutralization_tank_limestone_residence_time_minutes', models.PositiveIntegerField()),
                ('neutralization_tank_mgoh2_residence_time_minutes', models.PositiveIntegerField()),
                ('ph_in_final_neutralization_tank', models.FloatField()),
                ('neutralization_clarifier_flocculant_consumption_g_per_t', models.FloatField()),
                ('no_of_ccd_stages', models.PositiveIntegerField()),
                ('ccd_filtration_recovery_percent', models.FloatField()),
                ('flocculant_consumption_total_g_per_t', models.FloatField()),
                ('filtration_residual_moisture_in_cake_percent', models.FloatField()),
            ],
        ),
    ]
