# Generated by Django 3.2.24 on 2024-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0003_beneficiation2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurificationPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mg_sulfate_stages_evaporation', models.PositiveIntegerField(default=1)),
                ('mg_sulfate_stages_crystallization', models.PositiveIntegerField(default=3)),
                ('mg_removal_percentage', models.PositiveIntegerField(default=79)),
                ('centrifuge_cake_moisture_mg', models.PositiveIntegerField(default=4)),
                ('residual_magnesium_content_ppm', models.PositiveIntegerField(default=5)),
                ('mg_oh2_recycle_stream_pulp_density', models.PositiveIntegerField(default=30)),
                ('residual_calcium_content_ppm', models.PositiveIntegerField(default=100)),
                ('underflow_solids_density_calcium', models.PositiveIntegerField(default=5)),
                ('residual_calcium_content_ion_exchange', models.CharField(default='Proprietary', max_length=20)),
                ('residual_magnesium_content_ion_exchange', models.CharField(default='Proprietary', max_length=20)),
                ('residual_boron_content_ion_exchange', models.CharField(default='Proprietary', max_length=20)),
                ('lithium_carbonate_stages_crystallization', models.PositiveIntegerField(default=2)),
                ('lithium_carbonate_stages_bicarbonation', models.PositiveIntegerField(default=1)),
                ('second_stage_centrifuge_cake_moisture', models.PositiveIntegerField(default=20)),
                ('zld_centrifuge_cake_moisture', models.PositiveIntegerField(default=15)),
                ('dryer_discharge_moisture', models.FloatField(default=0.1)),
                ('jet_mill_discharge_particle_size', models.PositiveIntegerField(default=6)),
                ('cooler_discharge_temperature', models.PositiveIntegerField(default=40)),
                ('notes', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
