# Generated by Django 3.2.24 on 2024-02-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0004_purificationplant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiation',
            new_name='mines',
        ),
    ]
