# Generated by Django 3.2.24 on 2024-02-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0005_rename_beneficiation_mines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficiation2',
            new_name='beneficiation',
        ),
    ]
