# Generated by Django 3.2.24 on 2024-02-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortintervalcontrol', '0006_rename_beneficiation2_beneficiation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurificationPlant',
            new_name='ProcessPlant',
        ),
    ]
