# Generated by Django 3.2.24 on 2024-02-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_delete_bookingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
