# Generated by Django 3.2.24 on 2024-02-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_booking_no_of_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_MineTPH', models.PositiveIntegerField()),
                ('ScrubberTPH', models.PositiveIntegerField()),
                ('ThickenerTPH', models.PositiveIntegerField()),
                ('CoarseGangueM3PH', models.PositiveIntegerField()),
                ('RecycleWaterM3PH', models.PositiveIntegerField()),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tons', models.PositiveIntegerField()),
                ('Grade', models.PositiveIntegerField()),
                ('Manual_Tons', models.PositiveIntegerField()),
                ('no_of_guests', models.PositiveIntegerField()),
                ('Notes', models.CharField(max_length=200)),
            ],
        ),
    ]
