# Generated by Django 3.2.24 on 2024-02-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_beneficiation_mine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='no_of_guests',
        ),
    ]
